version: "3.8"
services:
  cdm_loader:
    build: .
    environment:
      DB_TYPE: ${DB_TYPE}
      DB_SERVER: ${DB_SERVER}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DRIVER_PATH: ${DRIVER_PATH}
      DB_SCHEMA: ${DB_SCHEMA}
      CSV_PATH: ${CSV_PATH}
      CDM_VERSION: ${CDM_VERSION}
      SYNTHEA_VERSION: ${SYNTHEA_VERSION}
      SYNTHEA_SCHEMA: ${SYNTHEA_SCHEMA}
      SYNTHEA_CSV: ${SYNTHEA_CSV}
    command: ["python", "main.py"]
